# Generated by Django 5.0 on 2023-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ASEC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("sex", models.IntegerField(blank=True, null=True)),
                ("income", models.IntegerField(blank=True, null=True)),
                ("weights", models.FloatField(blank=True, null=True)),
                ("race", models.FloatField(blank=True, db_column="Race", null=True)),
                (
                    "marital_status",
                    models.FloatField(
                        blank=True, db_column="Marital_Status", null=True
                    ),
                ),
                (
                    "born_us",
                    models.FloatField(blank=True, db_column="Born_US", null=True),
                ),
            ],
            options={
                "db_table": "ASEC",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NHANES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sex", models.FloatField(blank=True, null=True)),
                ("age", models.FloatField(blank=True, null=True)),
                (
                    "weightinkg",
                    models.FloatField(blank=True, db_column="weightInKg", null=True),
                ),
                (
                    "heightincm",
                    models.FloatField(blank=True, db_column="heightInCm", null=True),
                ),
                ("bmi", models.FloatField(blank=True, db_column="BMI", null=True)),
                ("weights", models.FloatField(blank=True, null=True)),
                ("race", models.IntegerField(blank=True, db_column="Race", null=True)),
                (
                    "marital_status",
                    models.FloatField(
                        blank=True, db_column="Marital_Status", null=True
                    ),
                ),
                (
                    "born_us",
                    models.FloatField(blank=True, db_column="Born_US", null=True),
                ),
            ],
            options={
                "db_table": "NHANES",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
