# Generated by Django 5.0 on 2023-12-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_asec_nhanes_delete_mymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NHANES",
        ),
    ]
