# Generated by Django 5.0 on 2023-12-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_delete_nhanes"),
    ]

    operations = [
        migrations.CreateModel(
            name="NHANES",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sex", models.FloatField(blank=True, null=True)),
                ("age", models.FloatField(blank=True, null=True)),
                (
                    "weightinkg",
                    models.FloatField(blank=True, db_column="weightInKg", null=True),
                ),
                (
                    "heightincm",
                    models.FloatField(blank=True, db_column="heightInCm", null=True),
                ),
                ("bmi", models.FloatField(blank=True, db_column="BMI", null=True)),
                ("weights", models.FloatField(blank=True, null=True)),
                ("race", models.IntegerField(blank=True, db_column="Race", null=True)),
                (
                    "marital_status",
                    models.FloatField(
                        blank=True, db_column="Marital_Status", null=True
                    ),
                ),
                (
                    "born_us",
                    models.FloatField(blank=True, db_column="Born_US", null=True),
                ),
            ],
            options={
                "db_table": "NHANES",
                "managed": False,
            },
        ),
    ]
