# Generated by Django 5.0 on 2023-12-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_nhanes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nhanes",
            options={"managed": True},
        ),
    ]
