# Generated by Django 5.0 on 2023-12-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_nhanes_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nhanes",
            options={"managed": False},
        ),
    ]
