# Generated by Django 5.0 on 2023-12-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_nhanes_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asecfemale",
            fields=[
                ("index", models.IntegerField(primary_key=True, serialize=False)),
                ("age", models.PositiveSmallIntegerField()),
                ("sex", models.SmallIntegerField(choices=[(2, "Female"), (1, "Male")])),
                ("income", models.FloatField()),
                ("weights", models.FloatField()),
                (
                    "race",
                    models.SmallIntegerField(
                        choices=[(1, "White"), (2, "Black"), (3, "Asian"), (4, "Other")]
                    ),
                ),
                (
                    "marital_status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Married"),
                            (2, "Widowed/Divorced/Separated"),
                            (3, "Other"),
                        ]
                    ),
                ),
                ("born_us", models.SmallIntegerField(choices=[(0, "No"), (1, "Yes")])),
            ],
            options={
                "db_table": "AsecFemale",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Asecmale",
            fields=[
                ("index", models.IntegerField(primary_key=True, serialize=False)),
                ("age", models.PositiveSmallIntegerField()),
                ("sex", models.SmallIntegerField(choices=[(2, "Female"), (1, "Male")])),
                ("income", models.FloatField()),
                ("weights", models.FloatField()),
                (
                    "race",
                    models.SmallIntegerField(
                        choices=[(1, "White"), (2, "Black"), (3, "Asian"), (4, "Other")]
                    ),
                ),
                (
                    "marital_status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Married"),
                            (2, "Widowed/Divorced/Separated"),
                            (3, "Other"),
                        ]
                    ),
                ),
                ("born_us", models.SmallIntegerField(choices=[(0, "No"), (1, "Yes")])),
            ],
            options={
                "db_table": "AsecMale",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nhanesfemale",
            fields=[
                ("index", models.IntegerField(primary_key=True, serialize=False)),
                ("sex", models.SmallIntegerField(choices=[(2, "Female"), (1, "Male")])),
                ("age", models.FloatField()),
                ("weight_kg", models.FloatField()),
                ("height_cm", models.FloatField()),
                ("bmi", models.FloatField()),
                ("weights", models.FloatField()),
                (
                    "race",
                    models.SmallIntegerField(
                        choices=[(1, "White"), (2, "Black"), (3, "Asian"), (4, "Other")]
                    ),
                ),
                (
                    "marital_status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Married"),
                            (2, "Widowed/Divorced/Separated"),
                            (3, "Other"),
                        ]
                    ),
                ),
                ("born_us", models.SmallIntegerField(choices=[(0, "No"), (1, "Yes")])),
            ],
            options={
                "db_table": "NhanesFemale",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nhanesmale",
            fields=[
                ("index", models.IntegerField(primary_key=True, serialize=False)),
                ("sex", models.SmallIntegerField(choices=[(2, "Female"), (1, "Male")])),
                ("age", models.FloatField()),
                ("weight_kg", models.FloatField()),
                ("height_cm", models.FloatField()),
                ("bmi", models.FloatField()),
                ("weights", models.FloatField()),
                (
                    "race",
                    models.SmallIntegerField(
                        choices=[(1, "White"), (2, "Black"), (3, "Asian"), (4, "Other")]
                    ),
                ),
                (
                    "marital_status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Married"),
                            (2, "Widowed/Divorced/Separated"),
                            (3, "Other"),
                        ]
                    ),
                ),
                ("born_us", models.SmallIntegerField(choices=[(0, "No"), (1, "Yes")])),
            ],
            options={
                "db_table": "NhanesMale",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="asec",
            table="Asec",
        ),
        migrations.AlterModelTable(
            name="nhanes",
            table="Nhanes",
        ),
    ]
